### PR TITLE
Bug 1795750 - Bump version to 1.1.0

### PR DESCRIPTION
**Pull request by willdurand**
Bumping the version to hopefully fix https://bugzilla.mozilla.org/show_bug.cgi?id=1795750

### CODE REVIEW

**Comment by willdurand** [comment]
it does look like it's working as intended:

```
[task 2024-06-14T07:58:14.376Z] Applying config file: ./package.json
[task 2024-06-14T07:58:14.457Z] Building web extension from /builds/worker/checkouts/vcs
[task 2024-06-14T07:58:14.524Z] Your web extension is ready: /builds/worker/checkouts/vcs/web-ext-artifacts/quitter.xpi
[task 2024-06-14T07:58:14.538Z] Getting output from ['git', 'rev-parse', 'HEAD'] ...
[task 2024-06-14T07:58:14.538Z] Buildid version is 1.1.20240614.75759
[task 2024-06-14T07:58:14.538Z] Updating package.json version from 1.1.0 to 1.1.20240614.75759...
[task 2024-06-14T07:58:14.538Z] Updating ./manifest.json version...
[task 2024-06-14T07:58:14.538Z]     was 1.0, now 1.1.20240614.75759
[task 2024-06-14T07:58:14.538Z] Running ['npm', 'install'] ...
[task 2024-06-14T07:58:14.538Z] Running ['npm', 'run', 'build'] ...
[task 2024-06-14T07:58:14.538Z] Copying web-ext-artifacts/quitter.xpi to /builds/worker/artifacts/quitter.xpi
[task 2024-06-14T07:58:14.538Z] Add-on id quitter@mozilla.org matches the allowlist.
```

**Comment by willdurand** [comment]
[xpidump](https://williamdurand.fr/xpidump/) indicates the following for the dep-signed XPI built in this PR:

> ✅ This privileged add-on has the following ID in its manifest: quitter@mozilla.org. Its version is: 1.1.20240614.75759.
>
> 🔐 It has been signed with the staging root certificate. This add-on is dual-signed (PKCS#7 and COSE). The PKCS#7 digest algorithm is: SHA-256. The COSE algorithm is: ES256.

**Comment by willdurand** [comment]
I pushed a second commit to fix a linting warning:

```
Code                      Message                                      Description                                                                                File                   Line   Column
APPLICATIONS_DEPRECATED   Use "browser_specific_settings" instead of   The "applications" property in the manifest is deprecated and will no longer be accepted   manifest.json
                          "applications".                              in Manifest Version 3 and above.
```

**Comment by willdurand** [comment]
@jcristau r? thanks

**Review by jcristau — APPROVED** [review]

**Pull request merged**
